{% set name = "utm" %}
{% set version = "0.7.0" %}
{% set sha256 = "3c9a3650e98bb6eecec535418d0dfd4db8f88c8ceaca112a0ff0787e116566e2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - utm

about:
  home: https://github.com/Turbo87/utm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Bidirectional UTM-WGS84 converter for python.
  description: Bidirectional UTM-WGS84 converter for python.
  doc_url: https://github.com/Turbo87/utm
  dev_url: https://github.com/Turbo87/utm

extra:
  recipe-maintainers:
    - snowman2
    - Turbo87
