{% set name = "utm" %}
{% set version = "0.6.0" %}
{% set sha256 = "a3c169ceabec910b4eb98a544b686cc4a25eb555407dfb9cb5f685123d5fa07f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - utm

about:
  home: https://github.com/Turbo87/utm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Bidirectional UTM-WGS84 converter for python.
  description: Bidirectional UTM-WGS84 converter for python.
  doc_url: https://github.com/Turbo87/utm
  dev_url: https://github.com/Turbo87/utm

extra:
  recipe-maintainers:
    - snowman2
    - Turbo87
