travis:
  secure:
    BINSTAR_TOKEN: l6IFXFuA8uDlVRwTZM5kMpWxMT7rykxN0WAz3TjLUQo5oFdHO3005zUvW/AlrtGaEBIsURCCMg6NT5ZPgEY3/jeOrlr9bFnqWZXi4Z9Ql8S0HhYRK10rtzZ8JgbkFURGfdtQywN7EOmb3tMgqL2A2KdMZe2+ZmAYQBYzA0yLqqPkdSiZ2iayuDZKzNc2Hp0JTyxIbJGWb03NsL4xZjEaKaKtk5g1Gz2g0JWDPMR3q/DVOW6/xfI+WCOhbxc2uZu5AsGgP+m5vsKEiZAlnnMhsKsr7F3w7jkpgjqkcPNx7mbGAWCm3pnOKG/sDnwyoXkXIydckCJYHuqcty0VGiMu00Yzkhp52HY46kOUlPMIphInBfA8Fq+zdn4IlDYDj5VuGpuZzEqbOJAMwgtBq69ywwV1XFcG60nFJJ5eXtKlzkS2YdFw75cOdCvq7OjCo0py+CSb/iJGoac/dkeZ4Uy6Vx+ZnMu6qtsV7O+To1dvJQsMtulTQStL1HjhG/kxlzQSaDQhqtk5DHYKpWTLqpL6KrnF6SSjObK2THn12OaluToQ9/fbCUHI/yA5LiygzEtJsjlR1O8ep4CJUEm0sleewhOoVAn73nOLKr7584ZAALadEr055qRQjOngP6fXdDLZlb0VvY16iyJvZvHqyTPdspRAZDp7vEIzNQRag+B3QnY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
