travis:
  secure:
    BINSTAR_TOKEN: mNUD5QfLKu+byYJhom28orF/pKvVV1o/0pX4PeefLY0pymsfAs+PLlxwlGFEGlbi2oExpVIiJV+8uIeS7orZdQ+g6S0k2UL4KsoAmACumnY5A5ab6AoJplKjiBt3NFLO8+LlOIexe4iqf0p1nNdGTBqK3zjZ/0/RoV+C4yrOD/SApCGoqX5TUAchPOiDoFBXmZwGaYSQwx2sPoPobkmME5P/j8n32vzLMv6uWqEGLWUS9NjBpR9n2IMVFrlURUgnmfWVM8RQZgRaM4uW8Y1TCiHvKgPmcxKDO2cWnfAlLmr0sGscbWLgZDDumPTIdFNUnuo/qP+PwYQgc59z48v4lZflliOEkjWLDQG4C6NfIr9SAWzu31L+izOMGOXfgMMU/82H0DKKmyBTktSQrjM5vcSpUiDuo2n1CEkq2piQhdnSudWeonxxI6Y+eyCVjgxq5IaxWcrSxAuAjDxDngjsBd1ro6XmSOcBDdAnsMp1KmteMXC3rpJG+Gdg5TpoJeDCHhkcnd7n6QAhllsoQHbvyhBmC07Ui8yVPzoeQvar5pqFYbMLp/B/rViGjM454vrvrG16twYHotEsc79JusGH4b5YXycp+FcucW7laEnZIYXlbRbMPSvvWrYuaSsHBpS7znGUzsLo7n3F3D/m3XZ78KO3pcxf5/fPXTTid3Z1p7s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
