travis:
  secure:
    BINSTAR_TOKEN: kLjNcGxRgxPFrlEYXZO0Ojvv3VQTrZv/La8b5q5OE5nz7D2zzeBxcQKUM3hWvN7y4xi3OKihvUhRcjry5e/GysvdXPBhzHI7ZUbI2KMj9sFltWulqWf/GGwHSEhqBzGUOobyfYWjgDkhoZ/ttgSzvEiSegkfR/yGm2yDF7J3RZeQzXNo0QHT5HFan6Jx4MeflVAaVQBCEnPM0FIDuGGvY59er4N39z7B8pa1H9EnUXXL6D3qPbPpgU6zYfvamljHjXqiByHMw8vDiHBcdMk8EOz10RtLrXZ84fRpECAp4Wc8Z6m4II3vCq8Ykj6hPmZ3QgX49BkL3mP394LNoFNJ1SWePAxNRaxkNKTnBdx8Z6u+LCbaPrT4/WmOtAJ4w6fe3yA3PGLDaDXdlQc0CHrW/FzDKdNSVuSc+4gPvuFnwlTutv/snGF1tmHYrOZ0DtFy8MBh7K5AP7z9NHAZoXc2+Yu769J6pduYjBHJ2MUjUmBEbn8Jscn1Kt0JaZKJjxf3lTOPc/0kl0dpRrg9QeAHBgHAQ78gV5fbFCsR6RiIRvNNlqHK5kR0naF2I0LvIQRfV6kGWbzPcnbKzNHmo+JAQeby+1ttOWQJlyS90jAcE+6DcBtIjBojC1ozdjejFzYGl8AzQNq3CZ3uQjUECV/PIfrSBHQrwOGgSJ0C8V3PsV8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
